### ISSUE TITLE
not usable as go module due to git submodule not being initialized

### ISSUE THREAD

**Issue by ansemjo** [dsprenkels/sss-go#2]
I was converting a project of mine to use [go modules](https://github.com/golang/go/wiki/Modules) to be independent of `GOPATH` and compilation fails with:
```
go: finding github.com/dsprenkels/sss-go v0.1.2-0.20171030131311-7f0045c35e77
# github.com/dsprenkels/sss-go
../../../../go/pkg/mod/github.com/dsprenkels/sss-go@v0.1.2-0.20171030131311-7f0045c35e77/hazmat.go:3:11: fatal error: hazmat.h: No such file or directory
 // #include "hazmat.h"
           ^~~~~~~~~~
compilation terminated.
```

This is apparently due to https://github.com/golang/go/issues/24094#issuecomment-377559768, i.e. Git submodules not being initialized in go modules. And since this binding uses [dsprenkels/sss](https://github.com/dsprenkels/sss) in a submodule ..

```
$ ls -la ~/go/pkg/mod/github.com/dsprenkels/sss-go@v0.1.2-0.20171030131311-7f0045c35e77/
total 52
dr-xr-xr-x 1 ansemjo users  216 Feb 19 14:23 .
drwxr-xr-x 1 ansemjo users   86 Feb 19 14:23 ..
-r--r--r-- 1 ansemjo users   42 Feb 19 14:23 .editorconfig
-r--r--r-- 1 ansemjo users  275 Feb 19 14:23 .gitignore
-r--r--r-- 1 ansemjo users   75 Feb 19 14:23 .gitmodules
-r--r--r-- 1 ansemjo users 4742 Feb 19 14:23 hazmat.go
-r--r--r-- 1 ansemjo users 1354 Feb 19 14:23 hazmat_test.go
-r--r--r-- 1 ansemjo users 1098 Feb 19 14:23 LICENSE
-r--r--r-- 1 ansemjo users 2540 Feb 19 14:23 README.md
-r--r--r-- 1 ansemjo users 4785 Feb 19 14:23 sss.go
-r--r--r-- 1 ansemjo users 1606 Feb 19 14:23 sss_test.go
-r--r--r-- 1 ansemjo users   53 Feb 19 14:23 .travis.yml
-r--r--r-- 1 ansemjo users  625 Feb 19 14:23 util.go
```

**Comment by dsprenkels** [comment]
Thanks for the bug report.

I am not up to date on Go's packaging practices. Is there some kind of easy solution to this, or should I just plainly copy all the [sss](https://github.com/dsprenkels/sss) files to this repo?

**Comment by ansemjo** [comment]
Basically .. yes.

I am not entirely sure if there isn't another way or why this was allowed before using go modules .. but looking at https://github.com/icedream/go-bsdiff/commit/a703ebb606c7395a73dd15a5adb5287dd485d3fc this seems to be a common solution. I "fixed" my project similarly, just downloading archives and vendoring sss-go and its submodules in my repository: https://github.com/ansemjo/go-shamirsplit/commit/9b9ab5bfb11c974d85070e4becfa2d9f9854409d

You could add a [`go generate`](https://blog.golang.org/generate) command to download the code somehow but that would require manual interaction by the user and would not "just work".

Furthermore, if you look at the `ls -la` output above, the symlinks don't seem to be present in the go module.

**Comment by ansemjo** [comment]
As a suggestion: you might keep managing updates with submodules and run (maybe add that to the `pre-commit` hook locally?):

```sh
(cd sss/ && tar c . --dereference) | tar x ./{randombytes,sss,tweetnacl,hazmat}.{c,h}
```

Tar would pack them up while dereferncing the `randombytes/...` symlinks and finally overwrite the files in the working directory. There would be no symlinks in the topmost directory and adding as a hook would keep the files updated with the latest submodule commits "automagically".

---

Tested locally:

```sh
$ cat .git/hooks/pre-commit
#!/usr/bin/env bash

# update sources in topmost directory from referenced submodules
set -o pipefail
if (cd sss/ && tar c {randombytes,sss,tweetnacl,hazmat}.{c,h} --dereference) | tar x; then
  exec git add {randombytes,sss,tweetnacl,hazmat}.{c,h}
else
cat >&2 <<ERR
could not update source files from ./sss submodule
is it checked-out?
ERR
exit 1
fi
```

**Comment by dsprenkels** [comment]
Nice. I think I am going to take this option. :D

- [x] Copy [sss](https://github.com/dsprenkels/sss) files into repo.
- [x] Update `.travis.yml` with a check if the files are up to date.

**Comment by ansemjo** [comment]
Sweet! :tada:

One last thing: if you'd tag a new release `go get` would _"just work"_. It chooses the last published release by default, so right now you need to do `go get github.com/dsprenkels/sss-go@076b63ec5446` instead.

**Comment by dsprenkels** [comment]
Awesome. Thanks for the hint. The release is here: https://github.com/dsprenkels/sss-go/releases/tag/v0.1.2
